import { GAMEPLAY_CONFIG } from './config/gameplayConfig'
import { MODULE_CONFIG } from './config/moduleConfig'

export const GAME_CONFIG = {
    hud: {
        x: 12,
        scoreY: 12,
        livesY: 12,
        moduleSlotsX: 12,
        moduleSlotsY: 42,
        moduleSlotGap: 22,
        moduleSlotWidth: 116,
        moduleSlotHeight: 18,
        moduleSlotTextXOffset: 6,
        moduleSlotTextYOffset: 2,
        fontFamily: 'Courier New',
        fontSize: '20px',
        livesFontSize: '26px',
        moduleFontSize: '14px',
    },
    message: {
        fontSize: '32px',
    },
    starfield: {
        count: 70,
        minRadius: 1,
        maxRadius: 2,
        minSpeed: 35,
        maxSpeed: 110,
        color: 0xffffff,
        minAlpha: 0.25,
        maxAlpha: 0.8,
        loopOffset: 4,
        depth: -10,
    },
    player: {
        width: GAMEPLAY_CONFIG.player.width,
        height: GAMEPLAY_CONFIG.player.height,
        bottomOffset: GAMEPLAY_CONFIG.player.bottomOffset,
        speed: GAMEPLAY_CONFIG.player.speed,
        color: 0x00ff00,
        strokeWidth: 5,
        strokeColor: 0xffffff,
        defaultAlpha: 1,
        invulnerableAlpha: 0.4,
        invulnerableBlinkInterval: 100,
        initialLives: GAMEPLAY_CONFIG.player.initialLives,
        damagePerHit: GAMEPLAY_CONFIG.player.damagePerHit,
        invulnerabilityDuration: GAMEPLAY_CONFIG.player.invulnerabilityDuration,
    },
    bullet: {
        width: GAMEPLAY_CONFIG.bullet.width,
        height: GAMEPLAY_CONFIG.bullet.height,
        yOffset: GAMEPLAY_CONFIG.bullet.yOffset,
        speed: GAMEPLAY_CONFIG.bullet.speed,
        fireRate: GAMEPLAY_CONFIG.bullet.fireRate,
        color: 0xfacc15,
        destroyY: GAMEPLAY_CONFIG.bullet.destroyY,
        damage: GAMEPLAY_CONFIG.bullet.damage,
    },
    enemy: {
        width: GAMEPLAY_CONFIG.enemy.width,
        height: GAMEPLAY_CONFIG.enemy.height,
        speed: GAMEPLAY_CONFIG.enemy.speed,
        spawnRate: GAMEPLAY_CONFIG.enemy.spawnRate,
        minSpawnRate: GAMEPLAY_CONFIG.enemy.minSpawnRate,
        speedIncreasePerSecond: GAMEPLAY_CONFIG.enemy.speedIncreasePerSecond,
        spawnRateDecreasePerSecond: GAMEPLAY_CONFIG.enemy.spawnRateDecreasePerSecond,
        hitPoints: GAMEPLAY_CONFIG.enemy.hitPoints,
        carrierHitPoints: GAMEPLAY_CONFIG.enemy.carrierHitPoints,
        color: 0xef4444,
        carrierColor: 0xa78bfa,
        carrierSpawnChance: 25,
        carrierLabel: 'M',
        baseScale: 0.7,
        strokeWidth: 3,
        strokeColor: 0xffffff,
        healthBarWidth: 42,
        healthBarHeight: 5,
        healthBarOffsetY: 8,
        healthBarColor: 0x22c55e,
        healthBarBackgroundColor: 0x14532d,
    },
    module: MODULE_CONFIG,
    score: {
        initial: 0,
        hitReward: 1,
    },
    time: {
        millisecondsPerSecond: 1000,
    },
} as const

export type GameConfig = typeof GAME_CONFIG
